require_relative "../module/color_module"
require "colorize"
describe Game_Color do
  it "variable COLORS should have the following array" do
    expect(Game_Color::COLORS).to eq(['R', 'O', 'Y', 'B', 'I', 'C', 'V','P','G'])
  end
  it "should expect the size of array generated by level 1 to be 4" do
    expect(Game_Color.generated_color(1).size).to eq 4
  end
  it "should expect the size of array generated by level 2 to be 5" do
    expect(Game_Color.generated_color(2).size).to eq 5
  end
  it "should expect the size of array generated by level 3 to be 6" do
    expect(Game_Color.generated_color(3).size).to eq 6
  end
  it "should expect the size of the unique color array for display to be the same size of the color array passed to it" do
    color_array_one = ['R', 'O', 'Y', 'B']
    color_array_two = ['R', 'R', 'R', 'B']
    color_array_three =['R', 'R', 'R', 'B','B']
    color_array_four =['R', 'R', 'R', 'B','G','O']
    expect(Game_Color.unique_color_display(color_array_one).size).to be(color_array_one.size)
    expect(Game_Color.unique_color_display(color_array_two).size).to be(color_array_two.size)
    expect(Game_Color.unique_color_display(color_array_three).size).to be(color_array_three.size)
    expect(Game_Color.unique_color_display(color_array_four).size).to be(color_array_four.size)
  end
end
